<?php

namespace Acme\TutorialBundle\Repository;

use Acme\TutorialBundle\Entity\Answer;
use Acme\TutorialBundle\Entity\Question;
use Doctrine\ORM\EntityRepository;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends EntityRepository
{

    public function create($data, Question $question)
    {
        $obj = new Answer();

        $obj->setTextAnswer($data['textAnswer'])
            ->setCorrectAnswer($data['correctAnswer'])
            ->setQuestion($question);

        $this->_em->persist($obj);
        $this->_em->flush($obj);

        return $obj;
    }

    public function update($answer, Question $question)
    {
        $answer->setQuestion($question);
        $this->_em->persist($answer);
        $this->_em->flush();

        return $answer;
    }
}
