<?php

namespace Acme\TutorialBundle\Repository;

use Acme\TutorialBundle\Entity\Level;
use Acme\TutorialBundle\Entity\Question;
use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{

    public function findQuestionAndAnswerByLevel($id)
    {
        return $this->createQueryBuilder('q')
            ->select('q','a')
            ->where('q.level =$id')
            ->join('AcmeTutorialBundle:Answer', 'a')
            ->where('a.question = q.id')
            ->getQuery()
            ->getResult();
    }

    public function create($title, Level $level)
    {
        $obj = new Question();

        $obj->setTitle($title)
            ->setLevel($level);

        $this->_em->persist($obj);
        $this->_em->flush($obj);

        return $obj;
    }

    public function update($question, Level $level)
    {

        $question->setLevel($level);
        $this->_em->persist($question);
        $this->_em->flush();

        return $question;
    }

}
